DROP DATABASE IF EXISTS pixelmovies_bd;
CREATE DATABASE pixelmovies_bd;
use pixelmovies_bd;

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    DNI_CLIENTE VARCHAR(20) NOT NULL,
    NOMBRES_CLIENTE VARCHAR(100) NOT NULL,
    APELLIDO_PAT_CLIENTE VARCHAR(100) NOT NULL,
    APELLIDO_MAT_CLIENTE VARCHAR(100) NOT NULL,
    NUM_CELULAR_CLIENTE VARCHAR(15),
    FECHA_NACIMIENTO_CLIENTE DATE,
    CORREO_CLIENTE VARCHAR(100)
);

DROP TABLE IF EXISTS SALAS;
CREATE TABLE SALAS (
	ID_SALA INT AUTO_INCREMENT PRIMARY KEY,
    COD_SALA VARCHAR(7) NOT NULL,
    CAPACIDAD_SALA INT NOT NULL
);

DROP TABLE IF EXISTS PELICULAS;
CREATE TABLE PELICULAS (
	ID_PELICULAS INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_PELICULA VARCHAR (50)	NOT NULL,
    DIRECTOR_PELI VARCHAR (50)	NOT NULL,
    GENERO_PELI VARCHAR (30)	NOT NULL,
    DURACION_PELI TIME NOT NULL,
    IDIOMA_PELI VARCHAR (30) NOT NULL,
    CLASIFICACION_PELI VARCHAR (50)	NOT NULL
);

DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS (
	ID_PRODUCTO	INT	AUTO_INCREMENT PRIMARY KEY, 
	NOMBRE_PRODUCTO	VARCHAR (100)	NOT NULL,
	PRECIO_PRODUCTO	DECIMAL (8,2)	NOT NULL,
	MARCA_PRODUCTO VARCHAR (30)		NULL
);

DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE EMPLEADOS (
	ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    DNI_EMPLEADO VARCHAR(20) NOT NULL,
    NOMBRES_EMPLEADO VARCHAR(100) NOT NULL,
    APELLIDO_PAT_EMPLEADO VARCHAR(100) NOT NULL,
    APELLIDO_MAT_EMPLEADO VARCHAR(100) NOT NULL,
    NUM_CELULAR_EMPLEADO VARCHAR(15),
    FECH_NACIMIENTO_EMPLEADO DATE,
    CORREO_EMPLEADO VARCHAR(100)
);

DROP TABLE IF EXISTS RESERVAS;
CREATE TABLE RESERVAS (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    ID_SALA INT,
    ID_PELICULAS INT,
    FECHA_RESERVA Date,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID_SALA) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_PELICULAS) REFERENCES PELICULAS(ID_PELICULAS) ON DELETE CASCADE ON UPDATE CASCADE
);

/*INSERTOS EN CLIENTES*/
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('1234567', 'Juan', 'Perez', 'Sanchez', '999486261', '2002-10-07', 'juan.perez@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345678', 'Maria', 'Sanchez', 'Gimenez', '975203649', '2003-05-14', 'maria.geminis@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345680', 'Ana', 'Ramirez', 'Torres', '956437890', '2000-11-05', 'ana.ramirez@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345681', 'Luis', 'Gomez', 'Diaz', '912345678', '1985-07-19', 'luis.gomez@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345682', 'Carlos', 'Fernandez', 'Castro', '923456789', '1979-09-29', 'carlos.fernandez@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345683', 'Lucia', 'Martinez', 'Cruz', '934567890', '1992-01-14', 'lucia.martinez@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345684', 'Roberto', 'Santos', 'Rojas', '945678901', '1996-06-23', 'roberto.santos@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345685', 'Sara', 'Rios', 'Vega', '956789012', '2001-12-12', 'sara.rios@gmail.com');
INSERT INTO CLIENTES (DNI_CLIENTE, NOMBRES_CLIENTE, APELLIDO_PAT_CLIENTE, APELLIDO_MAT_CLIENTE, NUM_CELULAR_CLIENTE, FECHA_NACIMIENTO_CLIENTE, CORREO_CLIENTE)
VALUES ('2345686', 'Miguel', 'Lozano', 'Silva', '967890123', '1983-05-18', 'miguel.lozano@gmail.com');


/*INSERTOS EN SALAS*/
INSERT INTO SALAS (COD_SALA, CAPACIDAD_SALA) VALUES ('SALA001', 50);
INSERT INTO SALAS (COD_SALA, CAPACIDAD_SALA) VALUES ('SALA002', 150);
INSERT INTO SALAS (COD_SALA, CAPACIDAD_SALA) VALUES ('SALA003', 75);
INSERT INTO SALAS (COD_SALA, CAPACIDAD_SALA) VALUES ('SALA004', 140);
INSERT INTO SALAS (COD_SALA, CAPACIDAD_SALA) VALUES ('SALA005', 120);
INSERT INTO SALAS (COD_SALA, CAPACIDAD_SALA) VALUES ('SALA006', 50);
INSERT INTO SALAS (COD_SALA, CAPACIDAD_SALA) VALUES ('SALA007', 90);


/*INSERTOS EN PELICULAS*/
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('Spider-Man: No Way Home', 'Jon Watts', 'Superhéroes', '02:28:00', 'Español', 'ATP');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('El Gran Escape', 'John Sturges', 'Aventura', '02:52:00', 'Español', 'ATP');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('El Padrino', 'Francis Ford Coppola', 'Drama', '02:55:00', 'Inglés', 'PG-13');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('La La Land', 'Damien Chazelle', 'Musical', '02:08:00', 'Español', 'ATP');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('El Señor de los Anillos: La Comunidad del Anillo', 'Peter Jackson', 'Fantasía', '02:58:00', 'Español', 'PG-13');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('Titanic', 'James Cameron', 'Drama', '03:15:00', 'Español', 'PG-13');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('La Lista de Schindler', 'Steven Spielberg', 'Drama', '03:15:00', 'Español', 'PG-13');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('Jurassic Park', 'Steven Spielberg', 'Ciencia ficción', '02:07:00', 'Español', 'PG-13');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('El Caballero Oscuro', 'Christopher Nolan', 'Acción/Crimen/Drama', '02:32:00', 'Español', 'PG-13');
INSERT INTO PELICULAS (NOMBRE_PELICULA, DIRECTOR_PELI, GENERO_PELI, DURACION_PELI, IDIOMA_PELI, CLASIFICACION_PELI)
VALUES ('El Rey León', 'Roger Allers y Rob Minkoff', 'Animación - Musical - Drama', '01:28:00', 'Español', 'ATP');

/*INSERTOS EN PRODUCTOS*/
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Popcorn tamaño grande', 27.00, 'Orville Redenbacher');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Gaseosa vaso grande', 6.50, 'Inka Cola');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Gaseosa vaso chico', 3.50, 'Coca Cola');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Café', 5.00, 'Dell');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Popcorn tamaño mediano', 20.00, 'Orville Redenbacher');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Hot Dog', 14.50, 'Oscar Mayer');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Nachos con queso', 10.00, 'Tostitos');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Pretzels', 7.30, 'Rold Gold');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Papas fritas', 12.10, 'Pringles');
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, PRECIO_PRODUCTO, MARCA_PRODUCTO) VALUES ('Dulces', 5.00, 'Mars');

/*INSERTOS EN EMPLEADOS*/
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO) 
VALUES ('75368914', 'Andres Ernesto', 'Gallegos', 'Fuentes', '978015610', '1986-08-15', 'andres.gallegos@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO) 
VALUES ('19671345', 'Adriana Angy', 'Montes', 'Aranda', '900855111', '2001-03-20', 'adriana.montes@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO) 
VALUES ('43128756', 'Guillermo Sergio', 'Barrios', 'Huerta', '984268009', '1998-06-10', 'guillermo.barrios@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128757', 'Carmen Rosa', 'Delgado', 'Lopez', '951234567', '1985-02-14', 'carmen.delgado@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128758', 'Daniel Alonso', 'Fernandez', 'Garcia', '962345678', '1990-08-21', 'daniel.fernandez@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128759', 'Sandra Lucia', 'Paredes', 'Castillo', '973456789', '1992-11-05', 'sandra.paredes@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128760', 'Jose Manuel', 'Ramos', 'Salazar', '984567890', '1988-03-11', 'jose.ramos@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128761', 'Elena Sofia', 'Torres', 'Vargas', '995678901', '1995-10-09', 'elena.torres@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128762', 'Ricardo Andres', 'Gomez', 'Perez', '906789012', '1983-05-29', 'ricardo.gomez@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128763', 'Patricia Elena', 'Ortiz', 'Reyes', '917890123', '1997-09-17', 'patricia.ortiz@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128764', 'Miguel Antonio', 'Rios', 'Alvarez', '928901234', '1984-12-24', 'miguel.rios@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128765', 'Gabriela Maria', 'Jimenez', 'Morales', '939012345', '1999-01-18', 'gabriela.jimenez@example.com');
INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRES_EMPLEADO, APELLIDO_PAT_EMPLEADO, APELLIDO_MAT_EMPLEADO, NUM_CELULAR_EMPLEADO, FECH_NACIMIENTO_EMPLEADO, CORREO_EMPLEADO)
VALUES ('43128766', 'Julio Cesar', 'Castro', 'Ramirez', '940123456', '1991-07-15', 'julio.castro@example.com');

INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('password123', 'admin1', 'Pablo Perez');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('securePass456', 'admin2', 'Mateo Jheremy');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('admin789pass', 'admin3', 'Angel Bances');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('mySecretPass', 'admin4', 'Raul Rosas');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('changeMe2021', 'admin5', 'Gustavo Linares');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('letMeIn2022', 'admin6', 'Nicole Aguilar');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('strongPass!!', 'admin7', 'Kevin Velasquez');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('adminAccess2023', 'admin8', 'Andreh Quispe');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('passAdmin99', 'admin9', 'Edwin Mamani');
INSERT INTO admin_user (contrasenia_usuario, nombre_usuario, nombre_usuario_real)
VALUES ('keyAdmin007', 'admin10', 'Leonardo Yupanqui');

Select * from admin_user;
SELECT * FROM CLIENTES;
SELECT * FROM SALAS;
SELECT * FROM PELICULAS;
SELECT * FROM PRODUCTOS;
SELECT * FROM EMPLEADOS;
SELECT * FROM RESERVAS;
